version: "3.12"
services:
 db:
  image: postgres:14
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_USER=user
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=media_db
 api:
  build: .
  ports:
   - "8000:8000"
  depends_on:
   - db
  volumes:
   - ./media:/media